apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
data:
  DJANGO_SETTINGS_MODULE: "users_api.settings"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "usersdb"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5000/notify"
  DJANGO_DEBUG: "False"
  ALLOWED_HOSTS: ".ejemplo.com,localhost"