apiVersion: v1
kind: Secret
metadata:
  name: users-api-secrets
type: Opaque
data:
  DB_USER: dXNlcnN1c2Vy  # usersuser base64
  DB_PASSWORD: dXNlcnNwYXNz  # userspass base64
  DJANGO_SECRET_KEY: ZGVmYXVsdC1zZWNyZXQta2V5  # default-secret-key base64